algoritmo "calcularaareaquadrado"
// Função : A função é receber um valor e calcular a área do quadrado
// Autor : Pedro H. Rillo
// Data : 28/02/2024
// Seção de Declarações 
var

 area, lado: real

inicio

//entrada
escreva ("Digite o lado do quadrado: ")
leia (lado)

//processamento
area <- lado*lado,

//saida
escreva ("A área deste quadrado é: ",area)
// Seção de Comandos 
fimalgoritmo
